import React from 'react';

import type { Metadata } from 'next';
import { Fredoka } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import Header from '../components/header';
import Footer from '../components/footer';

const inter = Fredoka({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
